name: API Automation Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bookstore-api-tests:latest .

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -e BASE_URL=https://fakerestapi.azurewebsites.net \
            -v "$(pwd)/playwright-report:/app/playwright-report" \
            -v "$(pwd)/allure-results:/app/allure-results" \
            bookstore-api-tests:latest

      - name: Setup GitHub Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload Playwright report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-temp
          path: playwright-report/
          retention-days: 1

      - name: Download Playwright report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-temp
          path: playwright-report/

      - name: Deploy Playwright report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          force_orphan: true
      
      - name: Show report URL in summary
        if: always()
        run: |
          echo "## ðŸ“Š Playwright HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ”— **[Open Last Test Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.html)**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
      
      - name: Generate Allure report
        if: always()
        run: |
          docker run --rm -v "$(pwd)/allure-results:/app/allure-results" -v "$(pwd)/allure-report:/app/allure-report" \
            frankescobar/allure-docker-service:latest generate /app/allure-results -o /app/allure-report
      
      - name: Deploy Allure report to GitHub Pages ()
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: allure